parameters:
   stt_m1 : 'Huỷ đơn hàng'
   stt_1 : 'Chưa tiếp nhận'
   stt_2 : 'Đã tiếp nhận'
   stt_3 : 'Đã lấy hàng / Đã nhập kho' 
   stt_4 : 'Đã điều phối giao hàng/Đang giao hàng'
   stt_5 : 'Đã giao hàng/Chưa đối soát'
   stt_6 : 'Đã đối soát'
   stt_7 : 'Không lấy được hàng'
   stt_8 : 'Hoãn lấy hàng'
   stt_9 : 'Không giao được hàng'
   stt_10 : 'Delay giao hàng' 
   stt_11 : 'Đã đối soát công nợ trả hàng'
   stt_12 : 'Đã điều phối lấy hàng/Đang lấy hàng'
   stt_13 : 'Đơn hàng bồi hoàn'
   stt_20 : 'Đang trả hàng (COD cầm hàng đi trả)'
   stt_21 : 'Đã trả hàng (COD đã trả xong hàng)'
   stt_123 : 'Shipper báo đã lấy hàng'
   stt_127 : 'Shipper (nhân viên lấy/giao hàng) báo không lấy được hàng'
   stt_128 : 'Shipper báo delay lấy hàng'
   stt_45 : 'Shipper báo đã giao hàng'
   stt_49 : 'Shipper báo không giao được giao hàng'
   stt_410 : 'Shipper báo delay giao hàng' 
